server:
  port: 1298
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/daijiaqin/siyin-configservice.git
          username: 526821189@qq.com
          password: djq19910412